-- =============================================================================
-- 0022 — Discovery source seed: Google News per GCC country
--
-- Six pseudo-source rows, one per country. These are NOT authorities — they
-- are discovery engines (source_type = 'discovery_engine', ingestion_mode =
-- 'discovery'). Seeded pre-verified because what was verified live in this
-- session (docs/hybrid-discovery-architecture-2026-08-03.md) is the
-- DISCOVERY MECHANISM itself (Google News RSS returns real, parseable
-- results with a usable <source> tag), not any individual government
-- website's markup — the exact distinction the M7.5 "no guessed selectors"
-- rule exists to protect. No item from these sources is ever inserted into
-- legal_updates without first passing AI legal classification and the
-- Publishing Gate, same as every official source.
--
-- feed_url queries combine exact legal-action phrases (ministerial decision,
-- cabinet decision, executive regulation, decree, circular, official
-- gazette, cabinet, draft law) with the country name, `when:2d` for
-- freshness. Precision is deliberately not perfect — false positives are
-- filtered by the AI classifier, exactly as the architecture already
-- requires for every other source.
-- =============================================================================

-- Auto-generated by scratchpad/build_discovery_seed.mjs — Google News discovery feeds, one per GCC country.
insert into public.sources
  (country, authority_ar, authority_en, source_type, ingestion_mode, base_url, active,
   parser_type, feed_url, parser_config, allowed_domains, priority, poll_interval_minutes,
   config_status, confidence, verification_method, notes)
values
  ('SA', 'اكتشاف Google News — السعودية', 'Google News Discovery — Saudi Arabia', 'discovery_engine', 'discovery',
   'https://news.google.com/?gl=SA', true, 'rss', 'https://news.google.com/rss/search?q=(%22%D9%82%D8%B1%D8%A7%D8%B1%20%D9%88%D8%B2%D8%A7%D8%B1%D9%8A%22%20OR%20%22%D9%82%D8%B1%D8%A7%D8%B1%20%D9%85%D8%AC%D9%84%D8%B3%20%D8%A7%D9%84%D9%88%D8%B2%D8%B1%D8%A7%D8%A1%22%20OR%20%22%D9%84%D8%A7%D8%A6%D8%AD%D8%A9%20%D8%AA%D9%86%D9%81%D9%8A%D8%B0%D9%8A%D8%A9%22%20OR%20%22%D9%85%D8%B1%D8%B3%D9%88%D9%85%22%20OR%20%22%D8%AA%D8%B9%D9%85%D9%8A%D9%85%22%20OR%20%22%D8%A7%D9%84%D8%AC%D8%B1%D9%8A%D8%AF%D8%A9%20%D8%A7%D9%84%D8%B1%D8%B3%D9%85%D9%8A%D8%A9%22%20OR%20%22%D9%85%D8%AC%D9%84%D8%B3%20%D8%A7%D9%84%D9%88%D8%B2%D8%B1%D8%A7%D8%A1%22%20OR%20%22%D9%85%D8%B4%D8%B1%D9%88%D8%B9%20%D9%82%D8%A7%D9%86%D9%88%D9%86%22)%20%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9%20when%3A2d&hl=ar&gl=SA&ceid=SA:ar', '{}'::jsonb,
   array['news.google.com'], 3, 120, 'verified', 40, 'direct_crawl',
   'مصدر اكتشاف، وليس جهة رسمية. يزوّد المرشحين لبوابة النشر عبر تحليل الذكاء الاصطناعي؛ لا يُنشر منه شيء إلا بعد تصنيف قانوني وتحقق. راجع docs/hybrid-discovery-architecture-2026-08-03.md.'),
  ('AE', 'اكتشاف Google News — الإمارات', 'Google News Discovery — UAE', 'discovery_engine', 'discovery',
   'https://news.google.com/?gl=AE', true, 'rss', 'https://news.google.com/rss/search?q=(%22%D9%82%D8%B1%D8%A7%D8%B1%20%D9%88%D8%B2%D8%A7%D8%B1%D9%8A%22%20OR%20%22%D9%82%D8%B1%D8%A7%D8%B1%20%D9%85%D8%AC%D9%84%D8%B3%20%D8%A7%D9%84%D9%88%D8%B2%D8%B1%D8%A7%D8%A1%22%20OR%20%22%D9%84%D8%A7%D8%A6%D8%AD%D8%A9%20%D8%AA%D9%86%D9%81%D9%8A%D8%B0%D9%8A%D8%A9%22%20OR%20%22%D9%85%D8%B1%D8%B3%D9%88%D9%85%22%20OR%20%22%D8%AA%D8%B9%D9%85%D9%8A%D9%85%22%20OR%20%22%D8%A7%D9%84%D8%AC%D8%B1%D9%8A%D8%AF%D8%A9%20%D8%A7%D9%84%D8%B1%D8%B3%D9%85%D9%8A%D8%A9%22%20OR%20%22%D9%85%D8%AC%D9%84%D8%B3%20%D8%A7%D9%84%D9%88%D8%B2%D8%B1%D8%A7%D8%A1%22%20OR%20%22%D9%85%D8%B4%D8%B1%D9%88%D8%B9%20%D9%82%D8%A7%D9%86%D9%88%D9%86%22)%20%D8%A7%D9%84%D8%A5%D9%85%D8%A7%D8%B1%D8%A7%D8%AA%20when%3A2d&hl=ar&gl=AE&ceid=AE:ar', '{}'::jsonb,
   array['news.google.com'], 3, 120, 'verified', 40, 'direct_crawl',
   'مصدر اكتشاف، وليس جهة رسمية. يزوّد المرشحين لبوابة النشر عبر تحليل الذكاء الاصطناعي؛ لا يُنشر منه شيء إلا بعد تصنيف قانوني وتحقق. راجع docs/hybrid-discovery-architecture-2026-08-03.md.'),
  ('KW', 'اكتشاف Google News — الكويت', 'Google News Discovery — Kuwait', 'discovery_engine', 'discovery',
   'https://news.google.com/?gl=KW', true, 'rss', 'https://news.google.com/rss/search?q=(%22%D9%82%D8%B1%D8%A7%D8%B1%20%D9%88%D8%B2%D8%A7%D8%B1%D9%8A%22%20OR%20%22%D9%82%D8%B1%D8%A7%D8%B1%20%D9%85%D8%AC%D9%84%D8%B3%20%D8%A7%D9%84%D9%88%D8%B2%D8%B1%D8%A7%D8%A1%22%20OR%20%22%D9%84%D8%A7%D8%A6%D8%AD%D8%A9%20%D8%AA%D9%86%D9%81%D9%8A%D8%B0%D9%8A%D8%A9%22%20OR%20%22%D9%85%D8%B1%D8%B3%D9%88%D9%85%22%20OR%20%22%D8%AA%D8%B9%D9%85%D9%8A%D9%85%22%20OR%20%22%D8%A7%D9%84%D8%AC%D8%B1%D9%8A%D8%AF%D8%A9%20%D8%A7%D9%84%D8%B1%D8%B3%D9%85%D9%8A%D8%A9%22%20OR%20%22%D9%85%D8%AC%D9%84%D8%B3%20%D8%A7%D9%84%D9%88%D8%B2%D8%B1%D8%A7%D8%A1%22%20OR%20%22%D9%85%D8%B4%D8%B1%D9%88%D8%B9%20%D9%82%D8%A7%D9%86%D9%88%D9%86%22)%20%D8%A7%D9%84%D9%83%D9%88%D9%8A%D8%AA%20when%3A2d&hl=ar&gl=KW&ceid=KW:ar', '{}'::jsonb,
   array['news.google.com'], 3, 120, 'verified', 40, 'direct_crawl',
   'مصدر اكتشاف، وليس جهة رسمية. يزوّد المرشحين لبوابة النشر عبر تحليل الذكاء الاصطناعي؛ لا يُنشر منه شيء إلا بعد تصنيف قانوني وتحقق. راجع docs/hybrid-discovery-architecture-2026-08-03.md.'),
  ('QA', 'اكتشاف Google News — قطر', 'Google News Discovery — Qatar', 'discovery_engine', 'discovery',
   'https://news.google.com/?gl=QA', true, 'rss', 'https://news.google.com/rss/search?q=(%22%D9%82%D8%B1%D8%A7%D8%B1%20%D9%88%D8%B2%D8%A7%D8%B1%D9%8A%22%20OR%20%22%D9%82%D8%B1%D8%A7%D8%B1%20%D9%85%D8%AC%D9%84%D8%B3%20%D8%A7%D9%84%D9%88%D8%B2%D8%B1%D8%A7%D8%A1%22%20OR%20%22%D9%84%D8%A7%D8%A6%D8%AD%D8%A9%20%D8%AA%D9%86%D9%81%D9%8A%D8%B0%D9%8A%D8%A9%22%20OR%20%22%D9%85%D8%B1%D8%B3%D9%88%D9%85%22%20OR%20%22%D8%AA%D8%B9%D9%85%D9%8A%D9%85%22%20OR%20%22%D8%A7%D9%84%D8%AC%D8%B1%D9%8A%D8%AF%D8%A9%20%D8%A7%D9%84%D8%B1%D8%B3%D9%85%D9%8A%D8%A9%22%20OR%20%22%D9%85%D8%AC%D9%84%D8%B3%20%D8%A7%D9%84%D9%88%D8%B2%D8%B1%D8%A7%D8%A1%22%20OR%20%22%D9%85%D8%B4%D8%B1%D9%88%D8%B9%20%D9%82%D8%A7%D9%86%D9%88%D9%86%22)%20%D9%82%D8%B7%D8%B1%20when%3A2d&hl=ar&gl=QA&ceid=QA:ar', '{}'::jsonb,
   array['news.google.com'], 3, 120, 'verified', 40, 'direct_crawl',
   'مصدر اكتشاف، وليس جهة رسمية. يزوّد المرشحين لبوابة النشر عبر تحليل الذكاء الاصطناعي؛ لا يُنشر منه شيء إلا بعد تصنيف قانوني وتحقق. راجع docs/hybrid-discovery-architecture-2026-08-03.md.'),
  ('BH', 'اكتشاف Google News — البحرين', 'Google News Discovery — Bahrain', 'discovery_engine', 'discovery',
   'https://news.google.com/?gl=BH', true, 'rss', 'https://news.google.com/rss/search?q=(%22%D9%82%D8%B1%D8%A7%D8%B1%20%D9%88%D8%B2%D8%A7%D8%B1%D9%8A%22%20OR%20%22%D9%82%D8%B1%D8%A7%D8%B1%20%D9%85%D8%AC%D9%84%D8%B3%20%D8%A7%D9%84%D9%88%D8%B2%D8%B1%D8%A7%D8%A1%22%20OR%20%22%D9%84%D8%A7%D8%A6%D8%AD%D8%A9%20%D8%AA%D9%86%D9%81%D9%8A%D8%B0%D9%8A%D8%A9%22%20OR%20%22%D9%85%D8%B1%D8%B3%D9%88%D9%85%22%20OR%20%22%D8%AA%D8%B9%D9%85%D9%8A%D9%85%22%20OR%20%22%D8%A7%D9%84%D8%AC%D8%B1%D9%8A%D8%AF%D8%A9%20%D8%A7%D9%84%D8%B1%D8%B3%D9%85%D9%8A%D8%A9%22%20OR%20%22%D9%85%D8%AC%D9%84%D8%B3%20%D8%A7%D9%84%D9%88%D8%B2%D8%B1%D8%A7%D8%A1%22%20OR%20%22%D9%85%D8%B4%D8%B1%D9%88%D8%B9%20%D9%82%D8%A7%D9%86%D9%88%D9%86%22)%20%D8%A7%D9%84%D8%A8%D8%AD%D8%B1%D9%8A%D9%86%20when%3A2d&hl=ar&gl=BH&ceid=BH:ar', '{}'::jsonb,
   array['news.google.com'], 3, 120, 'verified', 40, 'direct_crawl',
   'مصدر اكتشاف، وليس جهة رسمية. يزوّد المرشحين لبوابة النشر عبر تحليل الذكاء الاصطناعي؛ لا يُنشر منه شيء إلا بعد تصنيف قانوني وتحقق. راجع docs/hybrid-discovery-architecture-2026-08-03.md.'),
  ('OM', 'اكتشاف Google News — عُمان', 'Google News Discovery — Oman', 'discovery_engine', 'discovery',
   'https://news.google.com/?gl=OM', true, 'rss', 'https://news.google.com/rss/search?q=(%22%D9%82%D8%B1%D8%A7%D8%B1%20%D9%88%D8%B2%D8%A7%D8%B1%D9%8A%22%20OR%20%22%D9%82%D8%B1%D8%A7%D8%B1%20%D9%85%D8%AC%D9%84%D8%B3%20%D8%A7%D9%84%D9%88%D8%B2%D8%B1%D8%A7%D8%A1%22%20OR%20%22%D9%84%D8%A7%D8%A6%D8%AD%D8%A9%20%D8%AA%D9%86%D9%81%D9%8A%D8%B0%D9%8A%D8%A9%22%20OR%20%22%D9%85%D8%B1%D8%B3%D9%88%D9%85%22%20OR%20%22%D8%AA%D8%B9%D9%85%D9%8A%D9%85%22%20OR%20%22%D8%A7%D9%84%D8%AC%D8%B1%D9%8A%D8%AF%D8%A9%20%D8%A7%D9%84%D8%B1%D8%B3%D9%85%D9%8A%D8%A9%22%20OR%20%22%D9%85%D8%AC%D9%84%D8%B3%20%D8%A7%D9%84%D9%88%D8%B2%D8%B1%D8%A7%D8%A1%22%20OR%20%22%D9%85%D8%B4%D8%B1%D9%88%D8%B9%20%D9%82%D8%A7%D9%86%D9%88%D9%86%22)%20%D8%B9%D9%85%D8%A7%D9%86%20when%3A2d&hl=ar&gl=OM&ceid=OM:ar', '{}'::jsonb,
   array['news.google.com'], 3, 120, 'verified', 40, 'direct_crawl',
   'مصدر اكتشاف، وليس جهة رسمية. يزوّد المرشحين لبوابة النشر عبر تحليل الذكاء الاصطناعي؛ لا يُنشر منه شيء إلا بعد تصنيف قانوني وتحقق. راجع docs/hybrid-discovery-architecture-2026-08-03.md.')
on conflict (country, authority_en) do nothing;

